# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-04 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_contact', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
